data/members.csv

Hi,
I started a new position at a new company today (@RedDoorAnalytics), this PR just updates my affiliation in the members csv file. Thanks!
Alessandro

Updating Alessandro's affiliation

---

_quarto.yml
blog.qmd
index.qmd

17 do we want to offer an rss feed

---

_quarto.yml
presentations.qmd

Adding presentations tab to website

---

slides/r-adoption-jan2023.qmd

R adoption slides

---

data/members.csv

Update from "Incyte" -> "Independent"

Update company affiliation of daniel leibovitz

---

presentations.qmd
slides/pharma-rug-mmrm-mar2023.qmd
slides/r-adoption-jan2023.qmd

minor update with
1. typo fix
2. title update
3. add link in presentations page

minor update

---

bayesian_mmrm_R_package.qmd
data/members.csv
data/news.csv

This PR proposes a page for the Bayesian MMRM workstream.

Propose Bayesian MMRM workstream page

---

_quarto.yml

Add menu link to Bayes MMRM package

---

data/news.csv

This PR adds a mention in `news.csv` for the [`brms.mmrm`](https://rconsortium.github.io/brms.mmrm/) R package.

Mention {brms.mmrm} package in news.csv

---

presentations.qmd
slides/asa-ssc-mmrm-nov2023.qmd

Slides presented for the lightning talk in ASA SSC meeting NOv 2023
- Subset of R/Pharma slides

add slides presented at asa-ssc meeting Nov 2023

---

presentations.qmd
slides/china-R-mmrm-nov2023.qmd

basically reuse content from slides/pharma-rug-mmrm-mar2023.qmd and slides/asa-ssc-mmrm-nov2023.qmd

add slides for China R conference

---

slides/china-R-mmrm-nov2023.qmd

Update the conference name and adjust fontsize
the slides looks different on local machine and on the deployed version in the font size; so I reduce it to make it fit in the page

update conference name and adjust font size

---

blog.qmd

closes https://github.com/RConsortium/asa-biop-swe-wg/issues/44

44: Make connection to R Bloggers

---

CNAME
_quarto.yml

part of #90
see e.g. https://github.com/quarto-dev/quarto-cli/discussions/3249 for background

90: try the verification

---

CNAME
_quarto.yml

90: roll back CNAME thing

---

CNAME
_quarto.yml

90: try CNAME one more time

---

_quarto.yml
contact_us.qmd

91: Add link or in-page for the GitHub Discussions

---

hexwall.qmd

add log messages to capture hexwall rendering

add log messages to hexwall run

---

.github/workflows/publish.yaml

force into render step gh token as env var

add to render step gh_token in env vars

---

.github/workflows/publish.yaml
_quarto.yml
blog/hexwall_post/hexwall_logo.svg
blog/hexwall_post/index.qmd
data/news.csv
hexwall.qmd

blog post describing the new hexwall

hexwall blog post

---

blog/2023-gswe4rp-workshops-wrapup/index.qmd
blog/20230210-bbs-swe-course-basel/index.qmd
blog/hexwall_post/index.qmd
blog/mmrm-video-nov-2022/index.qmd
blog/wg_announcement/index.qmd

add R categories to relevant blog posts

---

blog.qmd

add R category feed

---

_quarto.yml

136: use https for site url

---

computational-statistics.csl
guide.qmd
references.bib

add scope and references to openstatsguide

---

README.md
_quarto.yml
contact_us.qmd

This PR updates some URL (and language in the README file) after the repository transfer to the @openstatsware organisation.

URL Updates

---

guide.qmd

- alternative graphics using tabs in quarto (doesn't require quite a bit of repetition so not ideal in some ways)
- added design / planning topic (this has saved me many times!)
- added dependency management (my knowledge of Julia is low so sanity check welcomed)

Updates to guide.qmd

---

join_us.qmd

fix Daniel's email address, add Alessandro

Update Join Us page

---

data/members.csv

- update affiliation of Daniel
- add Isaac to HTA workstream
- add Adam and Audrey as new members

members update

---

sponsors.qmd

Proposing a black background on this figure (png file has "DarkBg" in the name, but actually has a transparent background)

add black background color to BBSW logo

---

slides/efspi-leaders-feb2025.qmd

@danielinteractive Could you have a look at this pdf summary I hope to share as a pre-read? I thought this might be an easier format and then would go over this content very quickly in the presentation.
The content is slightly tweaked from the 2024 R APAC presentation.

PDF summary of openstatsware
